// <auto-generated />
using System;
using Invoice_Api.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Invoice_Api.Migrations
{
    [DbContext(typeof(InvoiceContext))]
    [Migration("20260102102614_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Invoice_Api.Models.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte[]>("Timestamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("CustomerId");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            CustomerId = 1,
                            Name = "Molunguri, A"
                        },
                        new
                        {
                            CustomerId = 2,
                            Name = "Muhinyi, Mauda"
                        },
                        new
                        {
                            CustomerId = 3,
                            Name = "Antony, Abdul"
                        },
                        new
                        {
                            CustomerId = 4,
                            Name = "Smith, Ahmad"
                        });
                });

            modelBuilder.Entity("Invoice_Api.Models.Invoice", b =>
                {
                    b.Property<int>("InvoiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InvoiceId"));

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("InvoiceDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("InvoiceTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ProductTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SalesTax")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Shipping")
                        .HasColumnType("decimal(18,2)");

                    b.Property<byte[]>("Timestamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("InvoiceId");

                    b.HasIndex("CustomerId");

                    b.ToTable("Invoices");

                    b.HasData(
                        new
                        {
                            InvoiceId = 1,
                            CustomerId = 1,
                            InvoiceDate = new DateTime(2010, 1, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InvoiceTotal = 178.25m,
                            ProductTotal = 160.00m,
                            SalesTax = 12.00m,
                            Shipping = 6.25m
                        },
                        new
                        {
                            InvoiceId = 2,
                            CustomerId = 2,
                            InvoiceDate = new DateTime(2010, 1, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InvoiceTotal = 70.94m,
                            ProductTotal = 62.50m,
                            SalesTax = 4.69m,
                            Shipping = 3.75m
                        },
                        new
                        {
                            InvoiceId = 3,
                            CustomerId = 3,
                            InvoiceDate = new DateTime(2010, 1, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InvoiceTotal = 52.13m,
                            ProductTotal = 45.00m,
                            SalesTax = 3.38m,
                            Shipping = 3.75m
                        },
                        new
                        {
                            InvoiceId = 4,
                            CustomerId = 2,
                            InvoiceDate = new DateTime(2010, 1, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InvoiceTotal = 70.94m,
                            ProductTotal = 62.50m,
                            SalesTax = 4.69m,
                            Shipping = 3.75m
                        },
                        new
                        {
                            InvoiceId = 5,
                            CustomerId = 4,
                            InvoiceDate = new DateTime(2010, 1, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InvoiceTotal = 70.94m,
                            ProductTotal = 62.50m,
                            SalesTax = 4.69m,
                            Shipping = 3.75m
                        });
                });

            modelBuilder.Entity("Invoice_Api.Models.Invoice", b =>
                {
                    b.HasOne("Invoice_Api.Models.Customer", "Customer")
                        .WithMany("Invoices")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Invoice_Api.Models.Customer", b =>
                {
                    b.Navigation("Invoices");
                });
#pragma warning restore 612, 618
        }
    }
}
